name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - trunk
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch version.
          # https://github.com/golangci/golangci-lint/releases
          version: latest
          args: ./... --timeout=10m
