name: "PR Checks"

on:
  pull_request:
    branches:
      - trunk

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: 'go.mod'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          version: 2.12.5
          args: release --snapshot
